replicaCount: 1
order:
  image:
    repository: mohamedhakkim/learning-kafka-order
    tag: 667124e329f9975d05ab53c8637c64df19bad70b
    pullPolicy: IfNotPresent
shipping:
  image:
    repository: mohamedhakkim/learning-kafka-shipping
    tag: 667124e329f9975d05ab53c8637c64df19bad70b
    pullPolicy: IfNotPresent
invoicing:
  image:
    repository: mohamedhakkim/learning-kafka-invoicing
    tag: 667124e329f9975d05ab53c8637c64df19bad70b
    pullPolicy: IfNotPresent
