replicaCount: 1
order:
  image:
    repository: mohamedhakkim/learning-kafka-order
    tag: d798f751791f118c5adefe14e782d025155b727d
    pullPolicy: IfNotPresent
shipping:
  image:
    repository: mohamedhakkim/learning-kafka-shipping
    tag: d798f751791f118c5adefe14e782d025155b727d
    pullPolicy: IfNotPresent
invoicing:
  image:
    repository: mohamedhakkim/learning-kafka-invoicing
    tag: d798f751791f118c5adefe14e782d025155b727d
    pullPolicy: IfNotPresent
