apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicing
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: invoicing
  template:
    metadata:
      labels:
        app: invoicing
    spec:
      containers:
        - name: invoicing
          image: "{{ .Values.invoicing.image.repository }}:{{ .Values.invoicing.image.tag }}"
          imagePullPolicy: {{ .Values.invoicing.image.pullPolicy }}
          ports:
            - containerPort: 8080
