apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"
          imagePullPolicy: {{ .Values.order.image.pullPolicy }}
          ports:
            - containerPort: 8080
