apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: "{{ .Values.shipping.image.repository }}:{{ .Values.shipping.image.tag }}"
          imagePullPolicy: {{ .Values.shipping.image.pullPolicy }}
          ports:
            - containerPort: 8080
